# Generated by Django 4.1.7 on 2023-03-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Суперадмин'), (2, 'Админ музея'), (3, 'Пользователь')], default=0),
        ),
    ]
