# Generated by Django 4.1.7 on 2023-03-28 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_organization_logo_organization_subdomain_field'),
        ('shop', '0003_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='system_settings.organization'),
        ),
    ]
