# Generated by Django 4.1.7 on 2023-06-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0002_organization_logo_organization_subdomain_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
